[theme]
primaryColor = "#1f78d1"
backgroundColor = "#071019"
secondaryBackgroundColor = "#0f1720"
textColor = "#EAF2FF"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false